name: chili_flutter_storage_impl
description: Implementation of KeyValueStorage abstract class
version: 0.0.3
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3
  chili_flutter_storage:
    git:
      url: https://github.com/ChiliLabs/chili-flutter-storage.git
      ref: 0.0.2

dev_dependencies:
  flutter_lints: ^3.0.2
